
# A single stand-alone EC2 instance running the tokenserver.

TokenServer:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: m1.small
    ImageId: {"Ref": "TokenServerAMI"}
    KeyName: {"Ref": "AWSBoxDeployKey"}
    SecurityGroups:
      - {"Ref": "TokenSecurityGroup"}

TokenSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription:  awsboxen security group for picl-oldsync tokenserver
    SecurityGroupIngress:
      # Allow ssh from anywhere
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        CidrIp: "0.0.0.0/0"
      # Allow http access from anywhere
      - IpProtocol: "tcp"
        FromPort: "80"
        ToPort: "80"
        CidrIp: "0.0.0.0/0"


# A single stand-alone EC2 instance to act as a storage node.

StorageServer:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: m1.small
    ImageId: {"Ref": "StorageServerAMI"}
    KeyName: {"Ref": "AWSBoxDeployKey"}
    SecurityGroups:
      - {"Ref": "StorageSecurityGroup"}

StorageSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription:  awsboxen security group for picl-oldsync storage
    SecurityGroupIngress:
      # Allow ssh from anywhere
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        CidrIp: "0.0.0.0/0"
      # Allow http access from anywhere
      - IpProtocol: "tcp"
        FromPort: "80"
        ToPort: "80"
        CidrIp: "0.0.0.0/0"


# DNS Records for all the things.

DNSRecords:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    Comment: awsboxen dns records for picl-oldsync servers
    HostedZoneName: lcip.org.
    RecordSets:
      - Name: "auth.oldsync.dev.lcip.org."
        Type: "CNAME"
        TTL: 30
        ResourceRecords:
          - {"Fn::GetAtt": ["TokenServer", "PublicDnsName"]}
      - Name: "db1.oldsync.dev.lcip.org."
        Type: "CNAME"
        TTL: 30
        ResourceRecords:
          - {"Fn::GetAtt": ["StorageServer", "PublicDnsName"]}
